### PR TITLE
Fix list, do not split on comma

### LINKED ISSUE #99: Product Features splits on comma
This causes issues with incorrect formatting on details pages.

### PR DESCRIPTION
**Pull request by bstopp**
Fix #99 

Test URLs:
- Before: https://main--airlessco--hlxsites.hlx.page/emea/es/products/ss3350sp
- After: https://bugfix-features-list--airlessco--hlxsites.hlx.page/emea/es/products/ss3350sp

### CODE REVIEW

File: blocks/product-details/product-details.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ const detailsHtml = (placeholders, productInfo) => {
     fieldDiv.classList.add('details-item');
     const ul = document.createElement('ul');
 
-    productInfo[field].split(/[\n,]/g).forEach((line) => {
+    productInfo[field].split(/\r?\n|\r|\n/g).forEach((line) => {
```
Comment (helms-charity) [inline blocks/product-details/product-details.js:70]: ahhh there it was the whole time... Good fix.
